export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const QUANTITY_INCREMENT = "QUANTITY_INCREMENT"
export const QUANTITY_DECREMENT = "QUANTITY_DECREMENT"
