export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const QUANTITY_INCREMENT = "QUANTITY_INCREMENT"
export const QUANTITY_DECREMENT = "QUANTITY_DECREMENT"



// Filter

export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY"
export const TOGGLE_STOCK = "TOGGLE_STOCK"



// PRODUCT
export const LOAD_PRODUCT = "LOAD_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"